Repository SUVID-18/check_attendance_student, pull requests merged in 2023-11, with the labels that each got.

#64 feature/60
  lib/main.dart
  lib/model/lecture.dart
  lib/view/attendance.dart
  lib/view/attendance_fake.dart
  lib/view/attendance_history.dart
  lib/view/login.dart
  lib/view/main_page.dart
  lib/view/register_device.dart
  lib/view/settings_page.dart
  lib/view/styles.dart
  lib/view_model/attendance.dart
  lib/view_model/settings_page.dart
Labels: 기능 개선

#68 hotfix/login
  lib/model/lecture.dart
  lib/view/attendance.dart
  lib/view/styles.dart
Labels: 버그, 기능 개선

#69 feature/59
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/string.xml
  lib/main.dart
  lib/model/student.dart
  lib/view_model/login.dart
  pubspec.lock
  pubspec.yaml
  test/model_test.dart
Labels: 기능 개선

#72 hotfix/foreground_messaging
  lib/main.dart
Labels: hotfix

#73 hotfix/foreground_messaging_widget
  lib/main.dart
Labels: hotfix

#74 hotfix/notification_level_fix
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: hotfix

#75 hotfix/design
  lib/view/attendance.dart
  lib/view/attendance_history.dart
  lib/view_model/attendance_history.dart
Labels: hotfix

#76 release/v1.0
  .github/workflows/flutter-deploy.yaml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/string.xml
  lib/main.dart
  lib/model/lecture.dart
  lib/model/student.dart
  lib/view/attendance.dart
  lib/view/attendance_history.dart
  lib/view/login.dart
  lib/view/main_page.dart
  lib/view/register_device.dart
  lib/view/settings_page.dart
  lib/view/styles.dart
  lib/view_model/attendance.dart
  lib/view_model/attendance_history.dart
  lib/view_model/login.dart
  lib/view_model/register_device.dart
  lib/view_model/settings_page.dart
  pubspec.lock
  pubspec.yaml
  test/model_test.dart
  test/widget_test.dart
Labels: 기능 개선
